spring.application.name=si-701-mysql-select-query-demo-1

// Database 
spring.datasource.url=jdbc:mysql://localhost:3306/my_employee_schema
spring.datasource.username=root
spring.datasource.password=asdfghjkl
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

