spring.application.name=si-401-ftp-demo

ftp.host=127.0.0.1
ftp.port=21
ftp.username=usernamehere
ftp.password=passwordhere
ftp.remote.dir=/test
ftp.local.dir=C:/Users/shind/Downloads/ftp_temp
ftp.target.dir=C:/Users/shind/OneDrive/Desktop/FZshared/files
ftp.polling.interval=2000