spring.application.name=product_service
server.port=8082

# here client communicate with Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

## bydefault true but for understanding writing below
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

